"""
DISCLAIMER: this is provided for educataional purposes only. Use at your
own risk

Concatanetes the CSV files generated by a YouTube data takeout, and
formats the resulting file to make it suitable to use for uploader.py.
Note that all the paths are hard coded in the script

Usage:
    ❯ python csv-concat.py
    reading PLZ6Ih9wLHQ2H1u5cOpSWgVGsn8YLWMmdy.csv
    reading PLZ6Ih9wLHQ2Em6nwtgGZ9q-eBRlSSbDRU.csv
    reading PLZ6Ih9wLHQ2HDOnRZaKQSWz8R4II0163v.csv
    reading PLZ6Ih9wLHQ2FDvivyW8_xcp6qG4-D45yh.csv
    Created data/20220828T170021_data.csv
"""

from pathlib import Path
import pandas as pd
from datetime import datetime

SOURCE_DIR = Path("./playlists")
TARGET_DIR = Path("./data")


def with_timestamp(stem: str) -> str:
    dt = datetime.now()
    dt_string = dt.strftime("%Y%m%dT%H%M%S")
    return dt_string + "_" + stem


def get_csv_files():
    csvs = []
    for p in SOURCE_DIR.glob("*.csv"):
        print(f"reading {p.name}")
        playlist = Path(p.name).stem
        df = pd.read_csv(SOURCE_DIR / p.name, skiprows=3)
        df["Status"] = pd.Series(["" for x in range(len(df.index))])
        df["Playlist ID"] = pd.Series([playlist for x in range(len(df.index))])
        csvs.append(df)
    return pd.concat(csvs)


def main():
    concatenated_df = get_csv_files()
    destination_csv = TARGET_DIR / with_timestamp("data.csv")
    concatenated_df.to_csv(destination_csv, index=False)
    print(f"Created {destination_csv}")


if __name__ == "__main__":
    main()
