## _config:
##    dest: default dest path
##    srcRoot: path that will be prepended to all src
##    prependWithDigits: whether to add digits at start even if title is there
##    verbose: false
_config:
  # dest: /Volumes/WD2T/VIDEO/SHORTS/TRAILERS
  # dest: /Users/fritz/Documents/CONVERTED
  dest: /Volumes/WD2T/VIDEO/SHORTS/MUSIC/RECORDER/MR HINES
  srcRoot: /Users/fritz/Documents/SHORTS
instructions:
  - src: 'HINES 5 # Recorder Lesson 5 with Mr Hines - C Saw.mp4'
    cmd: split
    output:
      - filename: 'HINES 5 # 1 Lesson.mp4'
        # if no start and 1st item, start is the beginning
        start:
          minutes: 0
          seconds: 3
          milliseconds: 800
        end:
          minutes: 4
          seconds: 39
          milliseconds: 0
      - ref: 'HINES 5 # 2 Exercise 1'
        # if no start and not 1st item, start is previous output's end
        # if no duration, go to end
        start:
          minutes: 4
          seconds: 39
          milliseconds: 0
        end:
          minutes: 6
          seconds: 36
          milliseconds: 0
      - filename: 'HINES 5 # 3 end.mp4'
        # if no start and not 1st item, start is previous output's end
        # if no duration, go to end
  # # if nothing but output, use previous step's parts
  - src:
      - 'HINES 5 # 2 Exercise 1'
    cmd: join
    repeat: 3