## _config:
##    dest: default dest path
##    srcRoot: path that will be prepended to all src
##    prependWithDigits: whether to add digits at start even if title is there
##    verbose: false
_config:
  dest: /Users/fritz/Desktop/CONVERTED
  srcRoot: /Volumes/WD2T/VIDEO/SHORTS/EDUCATIONAL/WORD WORLD
instructions:
  # an array of objects, one per input file
  - src: A file.mp4
    # allows an overlap between clips by going back a bit at the start
    # of the first next one
    backtrack:
      seconds: 5
    # the new segments to be generated
    output:
      - title: part 1.mp4
        duration:
          minutes: 14
          seconds: 29
      # if no duration go to end
      - title: part 2.mp4
  - src: another film.mp4
    output:
      - title: part 3.mp4
        duration:
          minutes: 14
          seconds: 29